"""Correção do relacionamento entre User e PasswordResetToken

Revision ID: 21091600c6ee
Revises: e3472b3f47bb
Create Date: 2025-03-19 11:53:43.704094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21091600c6ee'
down_revision = 'e3472b3f47bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint('password_reset_token_token_key', type_='unique')
        batch_op.drop_constraint('password_reset_token_email_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('otp_secret',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('otp_secret',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('password_reset_token_email_fkey', 'user', ['email'], ['email'])
        batch_op.create_unique_constraint('password_reset_token_token_key', ['token'])
        batch_op.alter_column('token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
