"""Add profile image field to User

Revision ID: 534554c44ff7
Revises: 21091600c6ee
Create Date: 2025-03-26 09:51:12.638311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534554c44ff7'
down_revision = '21091600c6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
