"""nehum campo pode ser nullo

Revision ID: 93273f3f9631
Revises: e89c78dbfea8
Create Date: 2025-04-22 12:41:01.472686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93273f3f9631'
down_revision = 'e89c78dbfea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('providerType',
               existing_type=postgresql.ENUM('google', 'credentials', name='provider_type_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('providerType',
               existing_type=postgresql.ENUM('google', 'credentials', name='provider_type_enum'),
               nullable=True)
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
